CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(254)                         NOT NULL,
    name VARCHAR(250)                     NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uq_user_email UNIQUE (email)
    );

CREATE TABLE IF NOT EXISTS category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(200)                      NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id),
    CONSTRAINT uq_category_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS location (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    lat NUMERIC                                  NOT NULL,
    lon NUMERIC                                  NOT NULL,
    CONSTRAINT pk_location PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    annotation VARCHAR(2000)                    NOT NULL,
    category_id BIGINT                          NOT NULL,
    created_on TIMESTAMP WITHOUT TIME ZONE      NOT NULL,
    description VARCHAR(7000)                   NOT NULL,
    event_date TIMESTAMP WITHOUT TIME ZONE      NOT NULL,
    initiator_id BIGINT                         NOT NULL,
    location_id BIGINT                          NOT NULL,
    paid BOOLEAN                                NOT NULL,
    participant_limit int                       NOT NULL,
    request_moderation BOOLEAN                  DEFAULT TRUE,
    state VARCHAR(50)                           NOT NULL,
    title VARCHAR(120)                          NOT NULL,
    published_on TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT pk_event PRIMARY KEY (id),
    CONSTRAINT fk_event_category_id FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE CASCADE,
    CONSTRAINT fk_event_initiator_id FOREIGN KEY (initiator_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_event_location_id FOREIGN KEY (location_id) REFERENCES location (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE         NOT NULL,
    event_id BIGINT                             NOT NULL,
    requester_id BIGINT                         NOT NULL,
    status VARCHAR(50)                          NOT NULL,

    CONSTRAINT pk_request PRIMARY KEY (id),
    CONSTRAINT fk_request_event_id FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE,
    CONSTRAINT fk_request_requester_id FOREIGN KEY (requester_id) REFERENCES users (id) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS compilation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    pinned BOOLEAN                               NOT NULL,
    title VARCHAR(200)                           NOT NULL,

    CONSTRAINT pk_compilation PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilations_events (
    compilation_id BIGINT NOT NULL,
    event_id       BIGINT NOT NULL,

    CONSTRAINT pk_compilations_events PRIMARY KEY (compilation_id, event_id),
    CONSTRAINT fk_compilation FOREIGN KEY (compilation_id) REFERENCES compilation (id) ON DELETE CASCADE,
    CONSTRAINT fk_event FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE
);