version: '3.1'
services:
  stat-server:
    build: ./stat-service/server
    image: stat-service
    container_name: ewm_stat_server
    ports:
      - "9090:9090"
    depends_on:
      - stat-db
    environment:
      - STAT_DB=stat_db
      - STAT_DB_HOST=ewm_stat_db
      - STAT_DB_PORT=5432
      - STAT_USER=ewm
      - STAT_PASSWORD=ewm
      - JAVA_OPTS=Djdk.httpclient.HttpClient.log=errors,requests

  stat-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: ewm_stat_db
    environment:
      - POSTGRES_DB=stat_db
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm

  main-service:
    build: ./main-service
    image: main-service
    container_name: ewm_main_service
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - main-db
      - stat-server
    environment:
      - MAIN_DB=main_db
      - MAIN_DB_HOST=ewm_main_db
      - MAIN_DB_PORT=5432
      - MAIN_USER=ewm
      - MAIN_PASSWORD=ewm

  main-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: ewm_main_db
    environment:
      - POSTGRES_DB=main_db
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
